---
# file site.yml

- hosts: web
  roles:
   - common
   # docker
   - nginx

  #pre_tasks:
  #- debug: msg="Starting  to install docker"


  #post_tasks:
  #- debug: msg="Dcoker finished"
  
  pre_tasks:
  - debug: msg="Starting  to install nginx"


  post_tasks:
  - debug: msg="nginx finished"

